name: Deploy to neocities

# run on changes to main branch or when manually triggered
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 2

concurrency: # prevent concurrent deploys doing strange things
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: List contents of the working directory
        run: ls -al
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: src